# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hachahbo <hachahbo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/08 22:30:12 by hachahbo          #+#    #+#              #
#    Updated: 2023/04/29 22:51:32 by hachahbo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_printf.c ft_putchar.c \
		ft_putnbr.c ft_putstr.c \
		ft_puthex.c ft_putptr.c

NAME = libftprintf.a
OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME) : $(OBJS)
	@ar rc $(NAME) $(OBJS)

%.o: %.c ft_printf.h
	@cc -Wall -Wextra -Werror -c $<

clean :
	@rm -rf $(OBJS)

fclean : clean
	@rm -rf $(NAME)

re : fclean all
